name: Build - macOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  MAKEFLAGS: "-j 3"
  VCPKG_BINARY_SOURCES: "clear"

jobs:
  build:
    permissions:
      contents: read
    name: macos-release
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          brew install ninja cmake pkg-config

      - name: Get vcpkg commit ID
        id: vcpkg-step
        run: |
          vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ')
          echo "vcpkgGitCommitId=$vcpkgCommitId" >> $GITHUB_OUTPUT

      - name: Compute hash
        id: hash
        run: |
          hash=$(shasum -a 256 vcpkg.json | awk '{print toupper($1)}')
          echo "hash=$hash" >> $GITHUB_OUTPUT

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vcpkg/archives
            ${{ github.workspace }}/vcpkg/downloads
            ${{ github.workspace }}/vcpkg/installed
          key: vcpkg-macos15-x64-${{ steps.hash.outputs.hash }}
          restore-keys: vcpkg-macos15-x64-

      - name: Setup Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@a400452f634fe49e9f18d388aeb1809dcc642136
        env:
          VCPKG_PYTHON3: ${{ steps.python.outputs.python-path }}
          VCPKG_BINARY_SOURCES: "clear"
        with:
          vcpkgGitCommitId: ${{ steps.vcpkg-step.outputs.vcpkgGitCommitId }}
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Configure and Build
        env:
          VCPKG_BINARY_SOURCES: "clear"
        run: |
          # Usar x86_64-osx (Intel via Rosetta) evita bug do cppcodec no arm64
          cmake -G Ninja -S . -B build-macos \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=x64-osx \
            -DTOGGLE_BIN_FOLDER=ON \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
            -DTOGGLE_BOT_PROTECTION=OFF

          cmake --build build-macos --target otclient

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mythoria-mac
          path: build-macos/bin/
          if-no-files-found: error
