name: Build - Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: "-j 2"

jobs:
  build:
    name: windows-2022-release
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get vcpkg commit ID
        id: vcpkg-step
        shell: pwsh
        run: |
          $json = Get-Content vcpkg.json -Raw | ConvertFrom-Json
          $commit = $json.'builtin-baseline'
          echo "vcpkgGitCommitId=$commit" >> $env:GITHUB_OUTPUT

      - name: Install vcpkg
        uses: lukka/run-vcpkg@a400452f634fe49e9f18d388aeb1809dcc642136
        with:
          vcpkgGitCommitId: ${{ steps.vcpkg-step.outputs.vcpkgGitCommitId }}
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@v3.31.6

      - name: Configure and Build
        uses: lukka/run-cmake@main
        with:
          configurePreset: windows-release
          buildPreset: windows-release

      - name: Prepare artifact folder
        shell: pwsh
        run: |
          $artifactDir = "$env:GITHUB_WORKSPACE\artifacts"
          New-Item -ItemType Directory -Force -Path $artifactDir | Out-Null

          $exePath = Get-ChildItem -Recurse -Path $env:GITHUB_WORKSPACE -Filter "otclient*.exe" | Select-Object -First 1

          if (-not $exePath) {
            Write-Error "Not found otclient*.exe!"
            exit 1
          }

          Copy-Item $exePath.FullName -Destination $artifactDir

          $dlls = Get-ChildItem -Path $exePath.Directory.FullName -Filter "*.dll"
          foreach ($dll in $dlls) {
            Copy-Item $dll.FullName -Destination $artifactDir
          }

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mythoria-windows
          path: ${{ github.workspace }}/artifacts
