name: Build - macOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: "-j 2"

jobs:
  build:
    permissions:
      contents: read
    name: macos-release
    runs-on: macos-latest

    strategy:
      matrix:
        os: [macos-latest]
        buildtype: [macos-release]
        include:
          - os: macos-latest
            triplet: arm64-osx
            cmake_build_type: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get vcpkg commit ID
        id: vcpkg-step
        run: |
          vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ')
          echo "vcpkgGitCommitId=$vcpkgCommitId" >> $GITHUB_OUTPUT

      - name: Compute vcpkg.json hash
        id: hash
        run: |
          hash=$(shasum -a 256 vcpkg.json | awk '{print toupper($1)}')
          echo "hash=$hash" >> $GITHUB_OUTPUT

      - name: Cache vcpkg binary artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vcpkg/archives
            ${{ github.workspace }}/vcpkg/downloads
            ${{ github.workspace }}/vcpkg/installed
            ${{ github.workspace }}/vcpkg/buildtrees
          key: vcpkg-${{ matrix.os }}-${{ matrix.buildtype }}-${{ steps.hash.outputs.hash }}
          restore-keys: |
            vcpkg-${{ matrix.buildtype }}-

      - name: Setup Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@a400452f634fe49e9f18d388aeb1809dcc642136
        env:
          VCPKG_PYTHON3: ${{ steps.python.outputs.python-path }}
        with:
          vcpkgGitCommitId: ${{ steps.vcpkg-step.outputs.vcpkgGitCommitId }}
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@v3.31.6

      - name: Configure and Build
        run: |
          cmake -G Ninja -S . -B build-${{ matrix.buildtype }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} \
            -DTOGGLE_BIN_FOLDER=ON \
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF \
            -DTOGGLE_BOT_PROTECTION=OFF

          cmake --build build-${{ matrix.buildtype }} --target otclient

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mythoria-mac
          path: build-${{ matrix.buildtype }}/bin/
          if-no-files-found: error
